1. Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [2]:
import numpy as np
ar = np.arange(10,70)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69])

3. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np
ar = np.arange(0,9).reshape(3,3)
print(ar)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np
num = [1,2,0,0,4,0]
a = np.nonzero(num)
print(a)


(array([0, 1, 4], dtype=int64),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [5]:
import numpy as np
a = np.random.randint(100,size=(10,10))
a

array([[ 8, 87,  9, 95, 95, 76, 74, 12, 58, 79],
       [64, 91, 15, 59, 37, 44, 96, 61, 27, 89],
       [28, 64, 47, 31,  6, 90, 58, 85, 33, 35],
       [22, 75, 16, 40, 53, 37, 22, 96, 56, 85],
       [19,  9, 33, 78, 62,  3,  3, 88, 75, 45],
       [17, 40, 56, 92, 29, 89, 62, 66,  9, 95],
       [39, 23, 55, 43, 77, 23, 54, 96, 61, 94],
       [52, 15, 91, 87, 52, 39, 28, 99, 70, 76],
       [13,  5,  4, 37, 50, 75, 14, 79, 41, 42],
       [64, 47, 45, 78, 19, 96, 50, 67, 17, 90]])

6. Create a random vector of size 30 and find the mean value.

In [6]:
import numpy as np
z = np.random.random(30)
z.mean()
print(z)

[0.56786336 0.87114735 0.23961311 0.57698969 0.09664079 0.70446819
 0.16026114 0.61953379 0.73510792 0.95445675 0.60989106 0.60578417
 0.16412198 0.93817158 0.63719811 0.04279342 0.86146952 0.38929054
 0.07689444 0.99833093 0.29272372 0.61515406 0.71019196 0.36989288
 0.47244463 0.59386786 0.16252237 0.4816598  0.52211501 0.26731188]
